spring.application.name=mahjong-app

server.port=${PORT:8080}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.thymeleaf.cache=true

app.upload.dir=uploads/icons

#削除パスワード
app.admin.password=${APP_ADMIN_PASSWORD:admin}

#画像保存
#supabase.url=${SUPABASE_URL}
#supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}

supabase.url=${SUPABASE_URL:https://iimzeedsmmyxwhawrnlz.supabase.co}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:dummy}

# DB接続数を抑える
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=30000

# 1人あたりの目標試合数
app.target-games-per-player=16

# LINE BOT設定
line.bot.channel-token=${LINE_BOT_CHANNEL_TOKEN:}
line.bot.channel-secret=${LINE_BOT_CHANNEL_SECRET:}
line.bot.group-id=${LINE_BOT_GROUP_ID:}
line.bot.handler.path=/callback